feat : implementation api reviews count
hungryhub-team/hh-nuxt pull request #112
Opened 2023-03-21 08:38 UTC by afandi-siregar

https://3.basecamp.com/5190892/buckets/31702802/card_tables/cards/5961030735

2023-03-22 01:38 UTC, afif-hh requested changes

2023-03-22 01:38 UTC, afif-hh commented on api/restaurant/getReviewsCount.ts
> +export const responseReviewSchema = z.object({
ini ga mencerminkan respond backend deh
![image](https://user-images.githubusercontent.com/100819694/226778548-852a04e6-7ed1-43fa-b8ad-ca4873bb121d.png)

2023-03-22 01:38 UTC, afif-hh commented on api/restaurant/getReviewsCount.ts
> +    if (err instanceof ZodError) {
pakai `useHandleError.ts` di catch nya aja udah cukup

2023-03-22 01:38 UTC, afif-hh commented on partial/restaurant_detail/RestaurantBody.vue
> +    <RestaurantStarSummary :stars-count="reviewStarsCount" />
kenapa di panggil di restaurant body lagi, kan udah aku pindah di panggin di RestaurantHeader.vue

2023-03-22 01:38 UTC, afif-hh commented on partial/restaurant_detail/RestaurantPage.vue
> +      await restaurantDetailStore.getReviewsCount();
jgn di hit ketika load halaman restaurant, tapi pas bottom sheet nya kebuka, cukup fetch 1 kali, kalau datanya udah ada jgn fetch lagi

![image](https://user-images.githubusercontent.com/100819694/226779264-4be06237-cde7-477f-82f3-a4a2d7a0e50f.png)

2023-03-22 01:38 UTC, afif-hh commented on stores/restaurantDetail.ts
> +        this.reviewStarsCount = [
ini di kasih if dulu, cek `data` dulu sebelum data.attributes, terus panggil alert kalau error

2023-03-22 09:17 UTC, afandi-siregar commented on partial/restaurant_detail/RestaurantBody.vue
> +    <RestaurantStarSummary :stars-count="reviewStarsCount" />
ini untuk dekstop mas

2023-03-22 09:22 UTC, afandi-siregar commented on partial/restaurant_detail/RestaurantBody.vue
> +    <RestaurantStarSummary :stars-count="reviewStarsCount" />
![image](https://user-images.githubusercontent.com/112913518/226857289-1f6c2b9e-8a51-48e6-94f4-aeb3fd8dfb61.png)
aku liat di design begini gambarannya, yah walaupun gk tau itu udh fix atau belum, buat antisipasi aja mas, untuk gambaran sementara didesktop

2023-03-22 09:52 UTC, afandi-siregar commented on partial/restaurant_detail/RestaurantBody.vue
> +    <RestaurantStarSummary :stars-count="reviewStarsCount" />
jadi mau dihapus  aja mas?

2023-03-23 08:14 UTC, afandi-siregar commented
done mas @afif-hh

2023-03-23 08:55 UTC, merged