feat : search by dtp toolbar
hungryhub-team/hh-nuxt pull request #123
Opened 2023-03-28 03:57 UTC by afandi-siregar

https://3.basecamp.com/5190892/buckets/31702802/card_tables/cards/5980749306

2023-03-28 07:18 UTC, afif-hh requested changes

2023-03-28 07:18 UTC, afif-hh commented on partial/restaurant_detail/RestaurantToolbar.vue
> +import ToolbarFilter from "~/components/FilterToolbar.vue";
namanya disamakan dengan import nya

2023-03-28 07:18 UTC, afif-hh commented on components/FilterToolbar.vue
> +      class="flex h-[26px] w-full cursor-pointer flex-row items-center gap-x-2 rounded-[5px] bg-[#F6F6F6] p-2"
warnan jgn di hardcode coba cek di tailwindconfig file nya

2023-03-28 07:18 UTC, afif-hh commented on components/FilterToolbar.vue
> +  @apply flex h-[26px]  items-center justify-center rounded-full bg-[#F6F6F6] text-center shadow-none  #{!important};
`#{!important}` itu buat apa ?

2023-03-29 03:27 UTC, afandi-siregar commented on components/FilterToolbar.vue
> +  @apply flex h-[26px]  items-center justify-center rounded-full bg-[#F6F6F6] text-center shadow-none  #{!important};
itu sama kaya !important di css mas, biar bisa diubah warna dan beberapa styling yang ada didefault HhButton nya

2023-03-29 03:32 UTC, afandi-siregar commented
done mas @afif-hh

2023-03-29 04:11 UTC, merged