feat : package description ui
hungryhub-team/hh-nuxt pull request #124
Opened 2023-03-28 05:27 UTC by afandi-siregar

https://3.basecamp.com/5190892/buckets/31702802/card_tables/5869934491

2023-03-28 07:15 UTC, afif-hh requested changes

2023-03-28 07:15 UTC, afif-hh commented on components/package/PackageDescription.vue
> +  <div class="flex h-full flex-col gap-y-2 rounded-xl bg-[#FFE2E2] p-4">
warna nya jgn di hardcode coba cek di tailwindconfig

2023-03-28 07:15 UTC, afif-hh commented on components/package/PackageDescription.vue
> +    <div class="text-right text-base text-[#656C6F]">
warna ini juga

2023-03-28 07:15 UTC, afif-hh commented on components/package/PackageDescription.vue
> +  expiredDate: {
expired date coba di validasi pakai dayjs dengan result nya sama dengan Figma

2023-03-29 03:06 UTC, afif-hh commented on components/package/PackageDescription.vue
> +const props = defineProps({
kurang `defineOptions`

2023-03-29 03:39 UTC, afandi-siregar commented
done mas @afif-hh

2023-03-29 04:12 UTC, afif-hh approved these changes

2023-03-29 04:12 UTC, merged