feat: x days left
hungryhub-team/hh-nuxt pull request #125
Opened 2023-03-28 07:13 UTC by fandihungryhub

https://3.basecamp.com/5190892/buckets/31702802/card_tables/cards/5981068802

2023-03-28 07:23 UTC, afif-hh requested changes

2023-03-28 07:23 UTC, afif-hh commented on components/restaurant_detail/TextDaysLeft.vue
> +  <div class="px-[5px] bg-[#0009] w-fit rounded">
warna nya jgn di hardcode, coba di cek dulu di tailwindconfig file

2023-03-28 07:23 UTC, afif-hh commented on components/restaurant_detail/TextDaysLeft.vue
> +  const date = Date.parse(props.date);
pakai gini aja mas

`const dayjsInstance = dayjs(props.date, "format-string-nya-(misal yyyy-mm-dd)")
if(!dayjsInstance.isValid()){
return "Invalid date"
}
`

2023-03-28 09:36 UTC, fandihungryhub commented on components/restaurant_detail/TextDaysLeft.vue
> +  const date = Date.parse(props.date);
updated

2023-03-28 09:37 UTC, fandihungryhub commented on components/restaurant_detail/TextDaysLeft.vue
> +  <div class="px-[5px] bg-[#0009] w-fit rounded">
di tailwindconfig gak ada, mau di tambahin?

2023-03-29 02:55 UTC, afif-hh commented on components/restaurant_detail/TextDaysLeft.vue
> +  <div class="px-[5px] bg-[#0009] w-fit rounded">
iya mas boleh

2023-03-29 03:05 UTC, afif-hh commented on components/restaurant_detail/TextDaysLeft.vue
> +});
kurang `defineOptions()`

2023-03-29 03:35 UTC, fandihungryhub commented on components/restaurant_detail/TextDaysLeft.vue
> +});
updated

2023-03-29 04:13 UTC, afif-hh approved these changes

2023-03-29 04:13 UTC, merged