feat: featured package UI
hungryhub-team/hh-nuxt pull request #126
Opened 2023-03-28 07:14 UTC by fandihungryhub

https://3.basecamp.com/5190892/buckets/31702802/card_tables/cards/5980740588

2023-03-29 03:01 UTC, afif-hh requested changes

2023-03-29 03:01 UTC, afif-hh commented on components/restaurant_detail/FeaturedPackageImage.vue
> +    <img :src="props.imageSource" class="w-full rounded-3xl" />
pakai HhImage

2023-03-29 03:03 UTC, afif-hh commented on components/restaurant_detail/FeaturedPackage.vue
> +
kurang `defineOptions({ name: 'component name nya' })`

2023-03-29 03:03 UTC, afif-hh commented on components/restaurant_detail/FeaturedPackageImage.vue
> +    <img :src="props.imageSource" class="w-full rounded-3xl" />
kurang defineOptions juga

2023-03-29 03:49 UTC, fandihungryhub commented on components/restaurant_detail/FeaturedPackageImage.vue
> +    <img :src="props.imageSource" class="w-full rounded-3xl" />
updated

2023-03-29 03:49 UTC, fandihungryhub commented on components/restaurant_detail/FeaturedPackage.vue
> +
updated

2023-03-30 07:57 UTC, afif-hh approved these changes

2023-03-30 07:57 UTC, merged