feat : package badge ui
hungryhub-team/hh-nuxt pull request #127
Opened 2023-03-28 08:09 UTC by afandi-siregar

feat  : https://3.basecamp.com/5190892/buckets/31702802/card_tables/cards/5981066645

2023-03-28 09:51 UTC, afif-hh requested changes

2023-03-28 09:51 UTC, afif-hh commented on components/package/PackageBadge.vue
> +
kurang defineOptions() buat `name` nya

2023-03-28 09:52 UTC, afif-hh requested changes

2023-03-29 03:04 UTC, afif-hh commented on components/package/PackageBadge.vue
> +
kurang `defineOptions()` buat nama component

2023-03-29 03:59 UTC, afandi-siregar commented
done mas @afif-hh

2023-03-29 04:14 UTC, afif-hh approved these changes

2023-03-29 04:14 UTC, merged