feat: booking confirmation header card
hungryhub-team/hh-nuxt pull request #137
Opened 2023-03-31 04:29 UTC by fandihungryhub

https://3.basecamp.com/5190892/buckets/31862334/card_tables/cards/5985638915
https://3.basecamp.com/5190892/buckets/31862334/card_tables/cards/5985646500
all package type (ayce, pp, hah, xp)

2023-04-04 01:34 UTC, afif-hh requested changes

2023-04-04 01:34 UTC, afif-hh commented on components/booking/Confirmation/BookingCardImage.vue
> +        src="/image/sample-qrcode-small.png"
nama folder `component` nya c kecil, image qr nya dari props

2023-04-04 01:34 UTC, afif-hh commented on components/booking/Confirmation/BookingCardImage.vue
> +import HhImage from '@/components/HhImage.vue';
@ nya diganti ke ~ aja

2023-04-04 01:34 UTC, afif-hh commented on components/booking/Confirmation/BookingCardImage.vue
> +        <div><HhIcon /></div>
hhIcon buat apa mas ?

2023-04-04 01:34 UTC, afif-hh commented on components/booking/Confirmation/BookingCardImage.vue
> +    return { text: "PARTY<br>PACK", bgColor: "bg-mint-600", boxShadow: "box-shadow-pp", };
warna tipe package ada di tailwindconfig mas, bisa di cek

2023-04-04 01:34 UTC, afif-hh commented on components/booking/Confirmation/BookingCardImage.vue
> +.box-shadow-hah {
box shadown nya pakai warna di tailwindconfig mas

2023-04-04 01:34 UTC, afif-hh commented on components/booking/Confirmation/BookingHeader.vue
> +      <div class="mb-1.5 text-base text-white font-bold">Copper Buffet</div>
copper buffet masih hard code

2023-04-04 01:34 UTC, afif-hh commented on components/booking/Confirmation/BookingHeader.vue
> +import BookingCardImage from "@/components/booking/Confirmation/BookingCardImage.vue";
@ diganti ~

2023-04-04 01:34 UTC, afif-hh commented on components/booking/Confirmation/BookingHeader.vue
> +    type: String as PropType<"ayce" | "pp" | "hah" | "xp">,
proptype ayce dll bisa import dari SupportedPackageType di types/Pack

2023-04-04 01:34 UTC, afif-hh commented on components/booking/Confirmation/BookingHeader.vue
> +    default: null,
props yg penting di jadiin required aja mas, kyk adult, date time, package type

2023-04-04 01:34 UTC, afif-hh commented on components/booking/Confirmation/BookingHeader.vue
> +.bg-gradient-ayce {
dicoba pakai warna dari tailwindconfig, biar kalau ada perubahan code warna terpusat

2023-04-04 01:34 UTC, afif-hh commented on components/icons/HhIcon.vue
> +  <path d="M15.1621 6.49074V12.5791C15.1621 12.7016 15.0906 12.8138 14.9808 12.8605L14.0538 13.2574C13.8607 13.3402 13.6494 13.1935 13.6494 12.9779V10.6464L10.0866 12.1719V14.7519C10.0866 14.876 10.0
hh icon buat apa mas

2023-04-05 06:27 UTC, fandihungryhub commented on components/booking/Confirmation/BookingCardImage.vue
> +        src="/image/sample-qrcode-small.png"
updated

2023-04-05 06:27 UTC, fandihungryhub commented on components/booking/Confirmation/BookingCardImage.vue
> +import HhImage from '@/components/HhImage.vue';
updated

2023-04-05 06:27 UTC, fandihungryhub commented on components/booking/Confirmation/BookingCardImage.vue
> +        <div><HhIcon /></div>
<img width="825" alt="Screenshot 2023-04-05 at 10 10 33" src="https://user-images.githubusercontent.com/106644731/229971941-dd326edf-8eb5-44d5-9e05-2a9447b75c35.png">

2023-04-05 06:29 UTC, fandihungryhub commented on components/booking/Confirmation/BookingCardImage.vue
> +    return { text: "PARTY<br>PACK", bgColor: "bg-mint-600", boxShadow: "box-shadow-pp", };
gak sama mas

2023-04-05 06:29 UTC, fandihungryhub commented on components/booking/Confirmation/BookingCardImage.vue
> +.box-shadow-hah {
gak ada mas

2023-04-05 06:29 UTC, fandihungryhub commented on components/booking/Confirmation/BookingHeader.vue
> +      <div class="mb-1.5 text-base text-white font-bold">Copper Buffet</div>
updated

2023-04-05 06:30 UTC, fandihungryhub commented on components/booking/Confirmation/BookingHeader.vue
> +import BookingCardImage from "@/components/booking/Confirmation/BookingCardImage.vue";
updated

2023-04-05 06:30 UTC, fandihungryhub commented on components/booking/Confirmation/BookingHeader.vue
> +    type: String as PropType<"ayce" | "pp" | "hah" | "xp">,
updated

2023-04-05 06:30 UTC, fandihungryhub commented on components/booking/Confirmation/BookingHeader.vue
> +    default: null,
updated

2023-04-05 06:31 UTC, fandihungryhub commented on components/booking/Confirmation/BookingHeader.vue
> +.bg-gradient-ayce {
bikin linear-gradient nya susah mas

2023-04-05 06:32 UTC, fandihungryhub commented on components/icons/HhIcon.vue
> +  <path d="M15.1621 6.49074V12.5791C15.1621 12.7016 15.0906 12.8138 14.9808 12.8605L14.0538 13.2574C13.8607 13.3402 13.6494 13.1935 13.6494 12.9779V10.6464L10.0866 12.1719V14.7519C10.0866 14.876 10.0
<img width="825" alt="Screenshot 2023-04-05 at 10 10 33" src="https://user-images.githubusercontent.com/106644731/229975740-1801adc1-b1d4-4abb-8470-e44b745e5167.png">

2023-04-06 02:31 UTC, merged