feat : payment method UI
hungryhub-team/hh-nuxt pull request #141
Opened 2023-04-03 07:27 UTC by afandi-siregar

feat : https://3.basecamp.com/5190892/buckets/31862334/card_tables/cards/5985643554

2023-04-04 01:36 UTC, afif-hh requested changes

2023-04-04 01:36 UTC, afif-hh commented on components/booking/Confirmation/PaymentMethod.vue
> +      Credit/Debit Card
kalau payment method nya bukan credit card bakal nampilin apa ?

2023-04-04 01:36 UTC, afif-hh commented on components/booking/Confirmation/PaymentMethod.vue
> +      Credit/Debit Card
harusnya di handle

2023-04-04 10:38 UTC, afandi-siregar commented
done mas @afif-hh

2023-04-05 04:23 UTC, afif-hh approved these changes

2023-04-05 04:23 UTC, merged