feat: booking confirmation big group
hungryhub-team/hh-nuxt pull request #156
Opened 2023-04-12 04:22 UTC by fandihungryhub

2023-04-17 02:03 UTC, afif-hh requested changes

2023-04-17 02:03 UTC, afif-hh commented on components/HhAlert.vue
> +    <BookingSectionTitle
ini jgn pakai booking section title mas, soalnya konteks nya buat booking aja component itu, jadi bikin aja lagi

2023-04-17 07:05 UTC, fandihungryhub commented on components/HhAlert.vue
> +    <BookingSectionTitle
updated

2023-04-17 08:18 UTC, afif-hh requested changes

2023-04-17 08:18 UTC, afif-hh commented on components/booking/BookingSectionTitle.vue
> +});
perubahan di sini di balikin aja mas, kan udah bikin baru

2023-04-17 08:48 UTC, fandihungryhub commented on components/booking/BookingSectionTitle.vue
> +});
updated

2023-04-19 02:14 UTC, afif-hh approved these changes

2023-04-19 02:14 UTC, merged