Fix: booking confirmation header image logic
hungryhub-team/hh-nuxt pull request #157
Opened 2023-04-12 06:32 UTC by fandihungryhub

2023-04-14 06:18 UTC, afif-hh requested changes

2023-04-14 06:18 UTC, afif-hh commented on partial/booking/BookingConfirmation.vue
> +function onClickBackButton(link: string) {
hapus mas

2023-04-17 00:42 UTC, fandihungryhub commented on partial/booking/BookingConfirmation.vue
> +function onClickBackButton(link: string) {
updated

2023-04-17 02:06 UTC, afif-hh approved these changes

2023-04-17 02:06 UTC, merged