Feat: booking confirmation add flip animation card
hungryhub-team/hh-nuxt pull request #171
Opened 2023-04-17 07:36 UTC by fandihungryhub

https://3.basecamp.com/5190892/buckets/31862334/card_tables/cards/6047559095

2023-04-17 07:48 UTC, afif-hh requested changes

2023-04-17 07:48 UTC, afif-hh commented on components/booking/confirmation/BookingCardImage.vue
> +.flip-card-front {
remove

2023-04-17 07:48 UTC, afif-hh commented on components/booking/confirmation/BookingCardImage.vue
> -            class="h-[182px] rounded-xl"
jadi ga pakai height sekarang mas ?

2023-04-17 09:02 UTC, fandihungryhub commented on components/booking/confirmation/BookingCardImage.vue
> +.flip-card-front {
removed

2023-04-17 09:02 UTC, fandihungryhub commented on components/booking/confirmation/BookingCardImage.vue
> -            class="h-[182px] rounded-xl"
updated

2023-04-18 05:06 UTC, afif-hh approved these changes

2023-04-18 05:06 UTC, merged