fix: checkout page bug when use 0 point
hungryhub-team/hh-nuxt pull request #174
Opened 2023-04-18 04:52 UTC by fandihungryhub

https://3.basecamp.com/5190892/buckets/31126446/todos/6038769253#__recording_6057952187

2023-04-18 05:04 UTC, afif-hh requested changes

2023-04-18 05:04 UTC, afif-hh commented on stores/voucher.ts
> +      const defaultPrice =  bookingChargeStore.chargeObject.chargePrice + oldPoints;
kalau zero point hit API ulang aja mas

2023-04-18 05:30 UTC, fandihungryhub commented on stores/voucher.ts
> +      const defaultPrice =  bookingChargeStore.chargeObject.chargePrice + oldPoints;
updated

2023-04-18 06:52 UTC, afif-hh commented
is already tested ? @fandihungryhub

2023-04-18 08:04 UTC, fandihungryhub commented
> is already tested ? @fandihungryhub

mas @afif-hh I have tested it with :

- signed in account **First Timer** which account has point
- signed in my account that doesn't have point
- guest account

2023-04-19 01:37 UTC, afif-hh approved these changes

2023-04-19 01:37 UTC, merged