fix : bottom sheet if fully
hungryhub-team/hh-nuxt pull request #189
Opened 2023-04-26 06:57 UTC by afandi-siregar

fix : https://3.basecamp.com/5190892/buckets/31702802/card_tables/cards/6043471306

2023-04-27 09:02 UTC, afif-hh requested changes

2023-04-27 09:02 UTC, afif-hh commented on components/common/BottomSheet.vue
> +  console.log("setSheetHeight", sheetHeight);
remove

2023-04-27 09:02 UTC, afif-hh commented on partial/restaurant_detail/RestaurantHeader.vue
> +const titleBottomSheet = computed(() => {
diganti ke bottomSheet title,

2023-04-27 09:02 UTC, afif-hh commented on components/common/BottomSheet.vue
> +  const maxHeight = 100;
maxHeight nya di jadiin props aja, default nya 95, jgn di setting semua jadi 100

2023-05-01 23:56 UTC, afandi-siregar commented
done mas @afif-hh

2023-05-02 02:57 UTC, afif-hh approved these changes

2023-05-02 02:57 UTC, merged