feat: accept we travel together
hungryhub-team/hh-nuxt pull request #193
Opened 2023-04-27 02:45 UTC by hanggarHungry24

ticket basecamp: https://3.basecamp.com/5190892/buckets/31126446/todos/5916411103

2023-04-27 08:57 UTC, afif-hh requested changes

2023-04-27 08:57 UTC, afif-hh commented on partial/booking/BookingAcceptWeTravelTogether.vue
> +import ActivateButton from "@/section/booking/BookingAcceptWeTravelTogether/ActivateButton.vue";
nama folder nya pakai huruf kecil sama `_` mas

2023-04-27 08:57 UTC, afif-hh commented on partial/booking/BookingAcceptWeTravelTogether.vue
> +import { useBookingStore, useBookingChargeStore } from "@/stores/booking";
@ diganti ke ~

2023-04-27 08:57 UTC, afif-hh commented on partial/booking/BookingAcceptWeTravelTogether.vue
> +import { useUserVoucherStore, useVoucherStore } from "~~/stores/voucher";
remove double `~`

2023-04-27 08:57 UTC, afif-hh commented on partial/booking/BookingAcceptWeTravelTogether.vue
> +const { isAcceptWeTravelTogetherActive, weTravelTogether } =
kyk nya enak `isAcceptWeTravelTogetherActive` diganti ke `isAcceptWeTravelTogether` aja dan `weTravelTogether` ke `weTravelTogetherForm` mas

2023-04-27 08:57 UTC, afif-hh commented on section/booking/BookingAcceptWeTravelTogether/ActivateButton.vue
> +        src="@/assets/image/icon-accept-travel-together.png"
pakai ~ aja mas

2023-04-27 08:57 UTC, afif-hh commented on stores/booking.ts
> +    isAcceptWeTravelTogetherDisabled(state) {
diganti ke `isValidWetravelTogether` aja mas

2023-04-27 09:45 UTC, hanggarHungry24 commented on partial/booking/BookingAcceptWeTravelTogether.vue
> +import ActivateButton from "@/section/booking/BookingAcceptWeTravelTogether/ActivateButton.vue";
updated mas

2023-04-27 09:45 UTC, hanggarHungry24 commented on partial/booking/BookingAcceptWeTravelTogether.vue
> +import { useUserVoucherStore, useVoucherStore } from "~~/stores/voucher";
updated mas

2023-04-27 09:45 UTC, hanggarHungry24 commented on section/booking/BookingAcceptWeTravelTogether/ActivateButton.vue
> +        src="@/assets/image/icon-accept-travel-together.png"
updated mas

2023-04-27 09:45 UTC, hanggarHungry24 commented on stores/booking.ts
> +    isAcceptWeTravelTogetherDisabled(state) {
updated mas

2023-05-02 03:06 UTC, afif-hh approved these changes

2023-05-02 03:06 UTC, merged