feat: booking confirmation event
hungryhub-team/hh-nuxt pull request #199
Opened 2023-05-03 05:23 UTC by fandihungryhub

https://3.basecamp.com/5190892/buckets/31862334/card_tables/cards/6038383000

2023-05-03 10:20 UTC, afif-hh requested changes

2023-05-03 10:20 UTC, afif-hh commented on components/booking/confirmation/BookingHeader.vue
> +      <!--NuxtLink v-if="props.shareLink" :to="props.shareLink"
dihapus

2023-05-03 10:20 UTC, afif-hh commented on pages/hybrid/confirmation.vue
> +        setupDataValidation.error = true;
dikasih useHandleError mas

2023-05-04 03:11 UTC, fandihungryhub commented on components/booking/confirmation/BookingHeader.vue
> +      <!--NuxtLink v-if="props.shareLink" :to="props.shareLink"
updated

2023-05-04 03:11 UTC, fandihungryhub commented on pages/hybrid/confirmation.vue
> +        setupDataValidation.error = true;
updated

2023-05-04 05:15 UTC, afif-hh approved these changes

2023-05-04 05:15 UTC, merged