feat: corporate event
hungryhub-team/hh-nuxt pull request #200
Opened 2023-05-03 06:22 UTC by monytaa

link basecamp: https://3.basecamp.com/5190892/buckets/31702802/card_tables/cards/6092736078

2023-05-05 02:29 UTC, afif-hh requested changes

2023-05-05 02:29 UTC, afif-hh commented on stores/corporateEvent.ts
> +      const request = await validateEventId(this.eventId);
ganti jadi `response`

2023-05-05 02:29 UTC, afif-hh commented on stores/corporateEvent.ts
> +      this.isValid = false;
ini panggil action `resetState` aja

2023-05-05 02:29 UTC, afif-hh commented on api/common/validateEventId.ts
> +export const validateEventSchema = z.object({
yg di valdiate `validateEventSchema` aja kan ? yg dari API

2023-05-05 02:29 UTC, afif-hh commented on api/common/validateEventId.ts
> +      defaultErrorMessage,
ini kurang `errorPath`

2023-05-05 02:29 UTC, afif-hh commented on partial/restaurant_detail/RestaurantPage.vue
> +  console.log(restaurantId.value, "restoId");
hapus

2023-05-05 02:29 UTC, afif-hh commented on partial/restaurant_detail/RestaurantPage.vue
> +    eventForRestaurant.value = +restaurantId.value;
ada `+` typo kyk nya

2023-05-08 06:32 UTC, monytaa commented on stores/corporateEvent.ts
> +      const request = await validateEventId(this.eventId);
done

2023-05-08 06:32 UTC, monytaa commented on stores/corporateEvent.ts
> +      this.isValid = false;
done

2023-05-08 06:33 UTC, monytaa commented on api/common/validateEventId.ts
> +      defaultErrorMessage,
ok udh ditambahin

2023-05-08 09:20 UTC, afif-hh requested changes

2023-05-08 09:20 UTC, afif-hh commented on section/booking/BookingChargeSummary.vue
> +import { useCorporateEventStore } from "~/stores/corporateEvent";
jgn panggil store di sini, di lewatin props aja sebagai `allowShowPrice`

2023-05-08 09:20 UTC, afif-hh commented on section/booking/BookingConfirm.vue
> +        v-if="props.showTotalCharge"
ga perlu `props`

2023-05-08 09:20 UTC, afif-hh commented on services/book/createBooking.ts
> +    corporateEventId: z.string().optional(),
ini di jadiin z.string().or(z.number()) aja

2023-05-08 12:17 UTC, merged