feat: quick tab bar store page desktop (WIP)
hungryhub-team/hh-nuxt pull request #201
Opened 2023-05-03 08:28 UTC by hanggarHungry24

ticket basecamp: https://3.basecamp.com/5190892/buckets/32591430/card_tables/cards/6106281862

2023-05-03 10:25 UTC, afif-hh requested changes

2023-05-03 10:25 UTC, afif-hh commented on helpers/abbreviationLabelPackageType.ts
> +export function abbreviationLabelPackage(value: string): string {
ada `type` yg isinya handle ayce,pp, dll mas coba di cari

2023-05-03 10:25 UTC, afif-hh commented on helpers/abbreviationLabelPackageType.ts
> +      wording = "All You Can Eat";
ada helper nama nya `getPackageTypeFullName` mas

2023-05-03 10:25 UTC, afif-hh commented on partial/restaurant_detail/sticky_header_navigation/RestaurantStickyHeaderDesktop.vue
> +const useActive = await loadUseActiveLib();
ini coba di pindah ke onMounted nya component mas

2023-05-04 08:08 UTC, hanggarHungry24 commented on helpers/abbreviationLabelPackageType.ts
> +export function abbreviationLabelPackage(value: string): string {
updated mas pake getPackageTypeFullName

2023-05-04 08:08 UTC, hanggarHungry24 commented on helpers/abbreviationLabelPackageType.ts
> +      wording = "All You Can Eat";
updated mas pake getPackageTypeFullName

2023-05-09 05:21 UTC, closed without merging