feat : voucher countdown feature
hungryhub-team/hh-nuxt pull request #236
Opened 2023-05-12 07:26 UTC by hanggarHungry24

ticket basecamp : https://3.basecamp.com/5190892/buckets/31702802/card_tables/cards/6105621750

2023-05-12 11:09 UTC, afif-hh requested changes

2023-05-12 11:09 UTC, afif-hh commented on stores/packagetTicket.ts
> +    hasPackageTicket: (state) => state.packageTickets.length > 0,
`hasPackageTickets` mas

2023-05-12 11:09 UTC, afif-hh commented on partial/restaurant_detail/RestaurantPackageTicketSection.vue
> +  return new Date(nextResetAt.value).getTime();
ini kalau `nextResetAt` nya string kosong jadi `NaN` mas, kalau bisa pakai dayjs aja sih

![image](https://github.com/hungryhub-team/hh-nuxt/assets/100819694/290395dc-5d36-48fb-b517-af5de943d4ba)

2023-05-12 11:09 UTC, afif-hh commented on components/CountDown.vue
> +  time: 0,
ini kyk nya enak props nya jadi `YYYY-MM-DD HH:ss` mas, terus di validate pakai `dayjs().isValid()` juga

2023-05-12 11:09 UTC, afif-hh commented on components/CountDown.vue
> +  time: 0,
terus ganti nama jadi `dateTime`

2023-05-12 11:09 UTC, afif-hh commented on components/CountDown.vue
> +    <template v-for="item in timerCountdown" :key="item">
`key` nya primitive value aja mas jgn object, misal `item.id` dll

2023-05-15 03:49 UTC, hanggarHungry24 commented on components/CountDown.vue
> +const formatnum = (num: number) => (num < 10 ? "0" + num : String(num));
updated mas

2023-05-15 03:50 UTC, hanggarHungry24 commented on partial/restaurant_detail/RestaurantPackageTicketSection.vue
> +  return new Date(nextResetAt.value).getTime();
updated pake day js

2023-05-15 03:50 UTC, hanggarHungry24 commented on components/CountDown.vue
> +  time: 0,
updated

2023-05-18 07:46 UTC, merged