feat: add validation zod for getDistance & orderEstimation
hungryhub-team/hh-nuxt pull request #73
Opened 2023-03-07 09:45 UTC by hanggarHungry24

ticket basecamp :  

https://3.basecamp.com/5190892/buckets/31126446/todos/5907615957     https://3.basecamp.com/5190892/buckets/31126446/todos/5907622456

2023-03-07 09:47 UTC, hanggarHungry24 commented on api/book/getDistance.ts
> +    useReport({
im not sure is this the correct way to use useReport mas @afif-hh  ?

2023-03-07 10:06 UTC, afif-hh requested changes

2023-03-07 10:06 UTC, afif-hh commented on api/book/getDistance.ts
> +    min_distance: z.number(),
pakai camelCase mas

2023-03-07 10:06 UTC, afif-hh commented on api/book/getDistance.ts
> +    const responseData = data as z.infer<typeof getDistanceResponseSchema>;
respon nya di parse juga mas pakai zod, jadi bakal error kalau ga sesuai

2023-03-07 10:06 UTC, afif-hh commented on api/book/getDistance.ts
> +    useReport({
udah bener mas, `if` yg bawah" belum di useReport

2023-03-08 06:23 UTC, afif-hh requested changes

2023-03-08 06:23 UTC, afif-hh commented on api/book/getDistance.ts
> +    const defaultErrorMessage = `${DEFAULT_ERROR_MESSAGE}, failed to get distance`;
bisa pakai useHandleError kemarin mas

2023-03-08 06:23 UTC, afif-hh commented on api/book/orderTimeEstimation.ts
> +    const defaultErrorMessage = `${DEFAULT_ERROR_MESSAGE}, failed to get estimation data`;
semua pakai useHandleError mas di catch nya

2023-03-08 07:28 UTC, hanggarHungry24 commented on api/book/getDistance.ts
> +    const defaultErrorMessage = `${DEFAULT_ERROR_MESSAGE}, failed to get distance`;
udah di update mas

2023-03-13 02:42 UTC, afif-hh approved these changes

2023-03-13 02:43 UTC, merged